-- minimal schema (see README for details)
CREATE DATABASE IF NOT EXISTS concentrix_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE concentrix_db;
CREATE TABLE IF NOT EXISTS users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),email VARCHAR(120) UNIQUE,password VARCHAR(255),phone VARCHAR(20),vip_level TINYINT DEFAULT 1,balance DECIMAL(12,2) DEFAULT 0,credit_score INT DEFAULT 0,referral_code VARCHAR(20) UNIQUE,referred_by VARCHAR(20),is_banned TINYINT(1) DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS admins(id INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(60) UNIQUE,password VARCHAR(255),role ENUM('superadmin','admin','moderator') DEFAULT 'admin',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS vip_settings(id INT AUTO_INCREMENT PRIMARY KEY,vip_level TINYINT UNIQUE,commission_percent DECIMAL(5,2),daily_tasks INT,max_submissions INT);
CREATE TABLE IF NOT EXISTS products(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255),image VARCHAR(255),star_rating DECIMAL(2,1) DEFAULT 0,price DECIMAL(12,2),vip_required TINYINT DEFAULT 1,is_active TINYINT(1) DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS lottery_awards(id INT AUTO_INCREMENT PRIMARY KEY,product_id INT,vip_level TINYINT,min_award DECIMAL(12,2),max_award DECIMAL(12,2),UNIQUE(product_id,vip_level));
CREATE TABLE IF NOT EXISTS user_lottery_tasks(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,product_id INT,status ENUM('pending','completed','failed') DEFAULT 'pending',awarded_amount DECIMAL(12,2) DEFAULT 0,assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,completed_at TIMESTAMP NULL);
CREATE TABLE IF NOT EXISTS deposits(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,amount DECIMAL(12,2),status ENUM('pending','approved','rejected') DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,approved_at TIMESTAMP NULL);
CREATE TABLE IF NOT EXISTS withdrawals(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,amount DECIMAL(12,2),status ENUM('pending','approved','rejected') DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,approved_at TIMESTAMP NULL);
CREATE TABLE IF NOT EXISTS user_balance_transactions(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,amount DECIMAL(12,2),type ENUM('deposit','withdraw','award','task_commission','welcome_bonus'),description VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
INSERT INTO vip_settings(vip_level,commission_percent,daily_tasks,max_submissions) VALUES (1,0.50,35,3) ON DUPLICATE KEY UPDATE commission_percent=VALUES(commission_percent),daily_tasks=VALUES(daily_tasks),max_submissions=VALUES(max_submissions);
INSERT INTO vip_settings(vip_level,commission_percent,daily_tasks,max_submissions) VALUES (2,1.00,40,3) ON DUPLICATE KEY UPDATE commission_percent=VALUES(commission_percent),daily_tasks=VALUES(daily_tasks),max_submissions=VALUES(max_submissions);
INSERT INTO vip_settings(vip_level,commission_percent,daily_tasks,max_submissions) VALUES (3,2.50,50,3) ON DUPLICATE KEY UPDATE commission_percent=VALUES(commission_percent),daily_tasks=VALUES(daily_tasks),max_submissions=VALUES(max_submissions);
INSERT INTO vip_settings(vip_level,commission_percent,daily_tasks,max_submissions) VALUES (4,4.00,60,3) ON DUPLICATE KEY UPDATE commission_percent=VALUES(commission_percent),daily_tasks=VALUES(daily_tasks),max_submissions=VALUES(max_submissions);
INSERT INTO admins(username,password,role) VALUES('admin','$2y$10$WbZl6rGqvJd4r1Htdkqf2OqQnWm3q6F2y8mM1QH3C0H33a7cVfM9y','superadmin') ON DUPLICATE KEY UPDATE username=username;